// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_lose_10_times = "CgkIhvvyv8EGEAIQFw"; // <GPGSID>
        public const string achievement_10x_air_time = "CgkIhvvyv8EGEAIQEA"; // <GPGSID>
        public const string achievement_10x_big_lose = "CgkIhvvyv8EGEAIQGg"; // <GPGSID>
        public const string achievement_10000_points = "CgkIhvvyv8EGEAIQCg"; // <GPGSID>
        public const string achievement_buy_suv = "CgkIhvvyv8EGEAIQEg"; // <GPGSID>
        public const string achievement_250_points = "CgkIhvvyv8EGEAIQBw"; // <GPGSID>
        public const string achievement_5x_big_lose = "CgkIhvvyv8EGEAIQGQ"; // <GPGSID>
        public const string achievement_500_points = "CgkIhvvyv8EGEAIQCA"; // <GPGSID>
        public const string achievement_1_flip = "CgkIhvvyv8EGEAIQGw"; // <GPGSID>
        public const string achievement_1000_coins = "CgkIhvvyv8EGEAIQDA"; // <GPGSID>
        public const string achievement_50_points = "CgkIhvvyv8EGEAIQBQ"; // <GPGSID>
        public const string achievement_buy_buggy = "CgkIhvvyv8EGEAIQEQ"; // <GPGSID>
        public const string achievement_25_points = "CgkIhvvyv8EGEAIQBA"; // <GPGSID>
        public const string achievement_all_achievements = "CgkIhvvyv8EGEAIQHw"; // <GPGSID>
        public const string achievement_100_coins = "CgkIhvvyv8EGEAIQCw"; // <GPGSID>
        public const string achievement_100_points = "CgkIhvvyv8EGEAIQBg"; // <GPGSID>
        public const string achievement_50000_coins = "CgkIhvvyv8EGEAIQDg"; // <GPGSID>
        public const string achievement_10_flips = "CgkIhvvyv8EGEAIQHA"; // <GPGSID>
        public const string leaderboard_best_scores = "CgkIhvvyv8EGEAIQAQ"; // <GPGSID>
        public const string achievement_1000_points = "CgkIhvvyv8EGEAIQCQ"; // <GPGSID>
        public const string achievement_5x_air_time = "CgkIhvvyv8EGEAIQDw"; // <GPGSID>
        public const string achievement_buy_all_cars = "CgkIhvvyv8EGEAIQFQ"; // <GPGSID>
        public const string achievement_15_achievements = "CgkIhvvyv8EGEAIQHg"; // <GPGSID>
        public const string achievement_10000_coins = "CgkIhvvyv8EGEAIQDQ"; // <GPGSID>
        public const string achievement_buy_maston_artin = "CgkIhvvyv8EGEAIQFA"; // <GPGSID>
        public const string achievement_buy_beta_juliet = "CgkIhvvyv8EGEAIQEw"; // <GPGSID>
        public const string achievement_lose_5_times = "CgkIhvvyv8EGEAIQFg"; // <GPGSID>
        public const string achievement_10_points = "CgkIhvvyv8EGEAIQAA"; // <GPGSID>
        public const string achievement_5_achievements = "CgkIhvvyv8EGEAIQHQ"; // <GPGSID>
        public const string achievement_lose_25_times = "CgkIhvvyv8EGEAIQGA"; // <GPGSID>

}

